name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Eigen
        run: sudo apt-get install -y libeigen3-dev

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.0
        env:
          CIBW_BUILD: "cp311-manylinux_x86_64 cp312-manylinux_x86_64"
          CIBW_BEFORE_ALL: "yum install -y eigen3-devel || apt-get install -y libeigen3-dev"
          CIBW_ENVIRONMENT: 'EIGEN_INCLUDE="/usr/include/eigen3"'

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: wheelhouse/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1